name: seol_haru_check
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  ulid: ^2.0.1
  firebase_core: ^3.13.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  flutter_image_compress: ^2.4.0
  carousel_slider: ^5.0.0
  gap: ^3.0.1
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  flutter_bounceable: ^1.2.0
  flutter_riverpod: ^2.6.1
  table_calendar: ^3.2.0
  firebase_auth: ^5.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/
    - assets/fonts/
    - assets/fonts/pretendard/
    - assets/icons/
    - assets/icons/player/
    - assets/icons/chevrons/
    - assets/icons/emoji/
    - assets/icons/empty/
    - assets/icons/normal/
    - assets/icons/sns/
    - assets/icons/tab_bar/
    - assets/icons/palette/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
